### ISSUE TITLE
Feature request: Suppress stderr

### ISSUE THREAD

**Issue by aderito7** [jscutlery/semver#416]
Good day, team

Currently I'm running versioning of script within my nx monorepo against Azure Pipelines.
`nx version my-project` is being run in conjunction with other scripts such as `npm install`, etc, which should they fail for some reason I wish for the task to fail as well.
At the moment jscutlery/semver is writing outputs to stderr, which I was hoping to request a feature to suppress (if not redirect to stdlog).

```yml
- task: Bash@3
    inputs:
      targetType: 'inline'
      script: bash myscript.sh
      failOnStderr: true
```

**Comment by edbzn** [comment]
Hi @aderito7, I'm not sure to get it, semver writes to `stderr` even if it succeeds?

**Comment by aderito7** [comment]
@edbzn , it would appear so. At least the pipeline fails due to this

**Comment by edbzn** [comment]
@aderito7 can you give the output?

**Comment by aderito7** [comment]
![7c96096268498e5cd599c85cbb1b14b89f9206844f0911ede4a98342716385ef](https://user-images.githubusercontent.com/16321230/149594071-b1aff094-6f18-4987-a2b3-bb6aedb12e6d.png)

**Comment by aderito7** [comment]
Bump on this one.
Same issue is being experienced on gitlab pipeline
This has required adding:
```yml
version:
  allow_failure: true
  script:
  - nx affected:version
```

`ERROR: Job failed: command terminated with exit code 1`

Unfortunately `allow_failure` suppresses **all** errors.
