### ISSUE TITLE
Error: src refspec main does not match any

### ISSUE THREAD

**Issue by gabsmprocha** [jscutlery/semver#421]
Hi! Im using GitHub Actions as my CI/CD, so i have this job:

```
release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: npm ci
      - run: npx nx version project-name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I also have a target on my project.json 

```
"version": {
            "executor": "@jscutlery/semver:version",
            "options": {
                "commitMessageFormat": "chore(${projectName}): release version ${version}",
                "push": true,
                "baseBranch": "main"
            }
 }
```

when i executed the workflow, i receive this following message: 
**ℹ Run `git push --follow-tags origin HEAD` to publish
Error: error: src refspec main does not match any**

It's like the executor doesn't recognize the baseBranch parameter
I check my branch name with **git ls-remote** and  **git show-ref** command, and i can see  **<some SHA1>    refs/heads/main**

I'm forgetting something?
