### ISSUE TITLE
Possible to change baseBranch for version script

### ISSUE THREAD

**Issue by davidren-apt** [jscutlery/semver#463]
Suppose workflow is that:

1. Make code change in feature branch
2. Merge feature branch to main branch

Then this is the timing to execute version script like:

> $ git co main
> $ nx affected --target version

As currently the new code change is already pushed to `main` branch, if still set `--baseBranch` as `main` branch, the diff cannot be correctly computed.

__Question__:

Is it possible to change the `--baseBranch` with a specific commit id or just `HEAD~1`?

**Comment by edbzn** [comment]
Hi, 

It's not possible to use a specific commit ref with `--baseBranch`, that's why in this repository we are dealing with a `last-release` tag to know from which reference calculating changes. Here is our workflow:

```yml
- name: Version
  run: npx nx affected --base=last-release --target=version # calculating new version from last-release

- name: Tag last-release
  run: git tag -f last-release # tagging last release

- name: Push changes # pushing the last-release tag
```
