### ISSUE TITLE
Bug `--skipCommitTypes`

### ISSUE THREAD

**Issue by edbzn** [jscutlery/semver#533]
I noticed that it worked fine if I wrote commit messages like `chore(versioning): this is a test` but if I wrote it like `chore: this is a test`, it would not take `--skipCommitTypes` into account

_Originally posted by @zeroregard in https://github.com/jscutlery/semver/issues/374#issuecomment-1152178637_

**Comment by zeroregard** [comment]
I'm still experiencing this bug.
I edited every changelog of the projects using semver, and committed this change with the message:

```chore(versioning): added 'changelog generation initialized' for first version of all changelogs```

This is the step I have in my workflow:
```
      - name: Update application versions
        if: github.ref == env.MAIN_BRANCH
        shell: bash
        run: npm run nx -- run-many --target=version --all --skipCommitTypes=build,docs,ci,chore,refactor,style,test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Every project has the `version` target set like so:
```
"version": {
      "executor": "@jscutlery/semver:version",
      "options": {
        "preset": "conventional"
      }
    }
```
