### ISSUE TITLE
Cannot find module '@jscutlery/semver'

### ISSUE THREAD

**Issue by Jucian0** [jscutlery/semver#534]
Hi everyone, I'm trying to use this package in my Bitbucket pipeline, but I'm stuck on this error.

There are any reason to this happens?

This is my pipeline steps:

```    
- step: &build-develop
        name: Build develop
        caches:
          - node
        script:
          - git fetch origin master:refs/remotes/origin/master
          - yarn
          - npx nx affected --target=build --base=develop~1  --head=develop --parallel
        artifacts:
          - dist/**

    - step: &publish-develop
        name: Publish develops
        caches:
          - node
        script:
          - git fetch origin master:refs/remotes/origin/master
          - npx nx affected --target=version --releaseAs=prerelease --base=develop~1  --head=develop --parallel
          - npx nx affected --target=publish --base=develop~1  --head=develop --parallel
          - git push && git push --tags
```

Error:

```
Error: Unable to resolve @jscutlery/semver:version.
Cannot find module '@jscutlery/semver'
Require stack:
```
