### ISSUE TITLE
After generating the tag, the pipeline fails in gitlab ci.

### ISSUE THREAD

**Issue by hayawata3626** [jscutlery/semver#552]
After generating the tag, the pipeline fails.
It seems to be a problem when pushing the code.
Is there something wrong with my setup?

```
$ npx nx affected --target=version --base=$NX_BASE --parallel=1
 >  NX   Running target version for 2 project(s):
    - next-app
    - next-app-e2e
 
> nx run next-app:version
[next-app] 🟠 No previous version tag found, fallback to version 0.0.0.
        New version will be calculated based on all changes since first commit.
        If your project is already versioned, please tag the latest release commit with next-app@x.y.z and run this command again.
[next-app] 🆕 Calculated new version "0.1.0".
[next-app] 📜 Generated CHANGELOG.md.
[next-app] 📦 Committed "chore(next-app): release version 0.1.0".
[next-app] 🔖 Tagged "next-app@0.1.0".
[next-app] ❌ Error: error: src refspec main does not match any.
error: failed to push some refs to '[https://gitlab-ci-token:[MASKED]@gitlab.com/watarunrun/nx-next-release-note.git'](https://gitlab-ci-token:%5BMASKED%5D@gitlab.com/watarunrun/nx-next-release-note.git')
    at /builds/watarunrun/nx-next-release-note/node_modules/@jscutlery/semver/src/executors/common/exec.js:10:34
    at ChildProcess.exithandler (node:child_process:406:5)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

I did exactly what the document says.
https://github.com/jscutlery/semver#gitlab-ci

my .gitlab-ci.yml

```yaml
image: node:16

stages:
  - build
  - release

.distributed:
  interruptible: true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline --legacy-peer-deps
    - NX_HEAD=$CI_COMMIT_SHA
    - NX_BASE=${CI_MERGE_REQUEST_DIFF_BASE_SHA:-$CI_COMMIT_BEFORE_SHA}
  artifacts:
    paths:
      - node_modules/.cache/nx

build:
  stage: build
  extends: .distributed
  script:
    - npx nx affected --base=$NX_BASE --head=$NX_HEAD --target=build --parallel=3

release-app:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
  stage: release
  extends: .distributed
  variables:
    GIT_DEPTH: '0'
  script:
    - git config --global user.name "watarunrun"
    - git config --global user.email "top.men09@gmail.com"
    - git remote set-url origin https://gitlab-ci-token:${DEPLOY_KEY}@gitlab.com/watarunrun/nx-next-release-note.git
    - npx nx affected --target=version --base=$NX_BASE
    - git tag -f last-release
    - git push origin last-release --force -o ci.skip

```

I changed settings of project.json to generate CHANGELOG.md as follows.

```json
"version": {
      "executor": "@jscutlery/semver:version",
      "options": {
        "preset": "conventional",
        "tagPrefix": "${projectName}@",
        "push": true
      }
    }
```
