### ISSUE TITLE
GitHub Workflow not fetching the right tags (version)

### ISSUE THREAD

**Issue by Megajin** [jscutlery/semver#627]
Hi,

I am facing a strange "bug" in my GitHub Workflow (using this version: `"@jscutlery/semver": "^2.29.0"`). I have used lerna to publish our packages in our monorepo. Since lerna was taken over by nx, we switched to nx and changed our workflow accordingly. If I run this piece of code locally in my project.json:

```json
    "version": {
      "executor": "@jscutlery/semver:version",
      "options": {
        "baseBranch": "main",
        "preset": "conventional",
        "tagPrefix": "${projectName}@",
        "postTargets": ["array-utils:deploy", "array-utils:github"],
        "syncVersions": false,
        "push": true,
        "commitMessageFormat": "release(${projectName}): ${version}"
      },
      "dependsOn": ["build", "docs", "readme-generate"]
    },
```

everything works perfectly fine. The tags are fetched properly and the version bump works as expected:

```

> nx run array-utils:version --dryRun

[array-utils] 🆕 Calculated new version "1.2.2".
```

However in the workflow itself it fails to use the right tag or version from the package.json:

```
> nx run array-utils:version

[array-utils] 🟠 No previous version tag found, fallback to version 0.0.0.
        New version will be calculated based on all changes since first commit.
        If your project is already versioned, please tag the latest release commit with array-utils@x.y.z and run this command again.
[array-utils] 🆕 Calculated new version "0.0.1".
```

Here is the workflow.yaml causing this behaviour:

```yaml
name: Tests, Docs, Changelogs, Publish
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build_lint_test_docs_readme_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: "recursive"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "19.x"
          registry-url: https://registry.npmjs.org/
      - name: Install Repo deps
        run: yarn install
      - name: Configure CI Git User
        run: |
          git config --global user.email ci-bot@github.com
          git config --global user.name GitHub Actions
      - name: Run NX Tasks
        uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: version
          projects: array-utils
        env:
          NODE_AUTH_TOKEN: ${{ secrets.DREAM_BIT_UTILS_NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 📝 Automated Docs and Readmes
```

As you can see, I am using the right fetch-depth and submodules. Looking forward for any help.
the repository is publicly available: https://github.com/dream-bit-de/dream-bit-utils

**Comment by mauris** [comment]
@Megajin it's likely got to do with `fetch-depth: 0` - not fetching history on your release branch (or `main` branch if you're releasing from `main`) would cause issues with `@jscutlery/semver` not being able to detect tags and history/diffs.

**Comment by Megajin** [comment]
Hi @mauris that makes sense. However I am using: `actions/checkout@v3` where `fetch-depth: 0` means all history and tags. You can read about it here: https://github.com/actions/checkout#Fetch-all-history-for-all-tags-and-branches . 

Here is the commented part of the configuration mentioned in the repository of `actions/checkout@v3`

```yaml
- uses: actions/checkout@v3
  with:
    # Number of commits to fetch. 0 indicates all history for all branches and tags.
    # Default: 1
    fetch-depth: ''
```

On a side note: Wouldn't it be a good idea to provide a flag like `--fallBackToPackageJsonVersion` ?

**Comment by edbzn** [comment]
Fetch-depth 0 is the regular way to go, you could write a custom script if perf is impacted. 

We don't want to add new options to the executor, we already have too many and we will probably remove some of them in the next major version. The initial choice was made to work only with tags to calculate the new version, IMO we should keep this logic as simple as that, if tags are missing it's a setup issue.

**Comment by Megajin** [comment]
Alright everyone, I will close this issue since it looks like a setup malfunction. Once I'll find the root cause, I will post it in here.

**Comment by lougroshek** [comment]
@Megajin Any luck? I'm seeing the same issue. 

Output from checkout shows the tag being pulled down: 

```
   * [new branch]        update-env-vars-processing -> origin/update-env-vars-processing
   * [new branch]        update_env_vars         -> origin/update_env_vars
   * [new branch]        useContext-replace      -> origin/useContext-replace
   * [new tag]           last-release            -> last-release  # < ======= Here's the tag.
  /usr/bin/git branch --list --remote origin/master
    origin/master
  /usr/bin/git rev-parse refs/remotes/origin/master
  8d7779f38eae0a478b8fb5d2c9feb68b68390590
Determining the checkout info
```

Output from version command shows no tag found: 

```
Run nx run mi-apollo-client-utils:version

> nx run mi-apollo-client-utils:version

[mi-apollo-client-utils] 🟠 No previous version tag found, fallback to version 0.0.0.
        New version will be calculated based on all changes since first commit.
        If your project is already versioned, please tag the latest release commit with mi-apollo-client-utils-x.y.z and run this command again.
[mi-apollo-client-utils] 🆕 Calculated new version "0.0.1".
[mi-apollo-client-utils] 📜 Generated CHANGELOG.md.
[mi-apollo-client-utils] 📝 Updated package.json version.
[mi-apollo-client-utils] 📦 Committed "chore(mi-apollo-client-utils): release version 0.0.1".
[mi-apollo-client-utils] 🔖 Tagged "mi-apollo-client-utils-0.0.1".
```

Commit tagged is on master (base) branch, and setting baseBranch in library config and command:

```
"version": {
      "executor": "@jscutlery/semver:version",
      "options": {
        "preset": "conventional",
        "baseBranch": "master"
      }
    }
```

GHA yml: 

```yml
name: 'Version and Publish mi-apollo-client-utils'

on:
  push:
    branches:
      - master
    paths:
      - libs/mi-apollo-client-utils/**

jobs:
  release:
    container:
      image: ###
      volumes:
        - /tmp/.ssh:/root/.ssh
      options: --user root
    runs-on: [self-hosted]
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get tags
        run: git fetch --tags origin
      - name: Configure Git
        run: |
          git config --global user.email "${{github.actor}}@users.noreply.github.com"
          git config --global user.name "${{github.actor}}"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Install Dependencies
        run: |
          npm install nx -g
          npm install --legacy-peer-deps
      - name: Version
        shell: bash
        run: |
          nx run mi-apollo-client-utils:version --baseBranch=master
```
